### ISSUE TITLE
How could I return the value of star-rating to parent view component

### ISSUE THREAD

**Issue by x-bingxin** [Jamiek94/Vuejs-rating#1]
Hi there, thanks for your sharing,

I tried as you mentioned in readme file, and it worked well. One thing I met and want to be helped is, I  made the star-rating as a component, and then imported from view pages, I clicked star to rate, but how could I get the rating value from the parent view pages? 
`<div class="main-content">`
    	`<div class="section-eval-content">`
    		`<star-rating :value.sync="evalRating"></star-rating>`
    	`</div>`
    	`<input type="button" name="" class="eval-commit-btn bgOrange sure" value="Submit" @click="submitEval">`
    `</div>`

the `evalRating` is 0, and then I click the star set it to 4, but the `evalRating` is still 0.

**Comment by Jamiek94** [comment]
Sorry for the late response, for some reason I don't get notified about issues.

That's quite odd, the two way binding with ":value.sync" should work. (It does for me).

You could always just dispatch an event to the parent component:

```
watch : {
  value  : function(value){
    this.$dispatch('rate', value);
  }
}
```

In parent:

```
events: {
  rate: function(value){
    console.log(value);
  }
}
```

**Comment by x-bingxin** [comment]
Thank you  👍 , I will try that way
